import React from 'react';
import { Card, ListGroup, Badge } from 'react-bootstrap';
import { format } from 'date-fns';

function ReportDetails({ report }) {
if (!report) return null;
const renderJobcard = (data) => (
    <>
        <ListGroup.Item><strong>Status:</strong> <Badge bg="primary">{data.status}</Badge></ListGroup.Item>
        <ListGroup.Item><strong>Requester:</strong> {data.requester?.username}</ListGroup.Item>
        <ListGroup.Item><strong>Approver:</strong> {data.approver?.username}</ListGroup.Item>
        <ListGroup.Item><strong>Dilution:</strong> {data.Dilution?.name}</ListGroup.Item>
        <ListGroup.Item><strong>Hardware:</strong> {data.Hardware?.name || 'N/A'}</ListGroup.Item>
    </>
);

const renderInventory = (data) => (
    <>
        <ListGroup.Item><strong>Item Name:</strong> {data.name}</ListGroup.Item>
        <ListGroup.Item><strong>Quantity:</strong> {data.quantity} {data.unit}</ListGroup.Item>
        <ListGroup.Item><strong>Status:</strong> <Badge bg="success">{data.status}</Badge></ListGroup.Item>
        <ListGroup.Item><strong>Supplier:</strong> {data.supplier}</ListGroup.Item>
    </>
);

const renderHardware = (data) => (
    <>
        <ListGroup.Item><strong>Hardware Name:</strong> {data.name}</ListGroup.Item>
        <ListGroup.Item><strong>Status:</strong> {data.status ? <Badge bg="success">Active</Badge> : <Badge bg="secondary">Inactive</Badge>}</ListGroup.Item>
        <ListGroup.Item><strong>Last Maintenance:</strong> {data.lastMaintenanceDate ? format(new Date(data.lastMaintenanceDate), 'dd/MM/yyyy') : 'N/A'}</ListGroup.Item>
    </>
);

const renderConsumption = (data) => (
    <>
        <ListGroup.Item><strong>Item Consumed:</strong> {data.Inventory?.name}</ListGroup.Item>
        <ListGroup.Item><strong>Quantity Used:</strong> {data.quantityUsed} {data.Inventory?.unit}</ListGroup.Item>
        <ListGroup.Item><strong>Date:</strong> {format(new Date(data.consumptionDate), 'dd/MM/yyyy HH:mm')}</ListGroup.Item>
        <ListGroup.Item><strong>Related Jobcard ID:</strong> {data.jobcardId}</ListGroup.Item>
    </>
);

const renderDetails = () => {
    switch (report.reportType) {
        case 'Jobcard': return renderJobcard(report.Jobcard);
        case 'Inventory': return renderInventory(report.Inventory);
        case 'Hardware': return renderHardware(report.Hardware);
        case 'Consumption': return renderConsumption(report.Consumption);
        default: return <ListGroup.Item>No details available for this report type.</ListGroup.Item>;
    }
};

return (
    <Card className="mt-2">
        <Card.Body>
            <Card.Title>Details for Report #{report.reportId}</Card.Title>
            <ListGroup variant="flush">
                {renderDetails()}
                <ListGroup.Item><strong>Generated By:</strong> {report.User?.username}</ListGroup.Item>
                <ListGroup.Item><strong>Generated On:</strong> {format(new Date(report.generatedDate), 'dd/MM/yyyy HH:mm')}</ListGroup.Item>
            </ListGroup>
        </Card.Body>
    </Card>
);
}
export default ReportDetails;